"""
Critique Engine subsystem for AI Research Paper Critic (Phase 6).

The final synthesis layer: it turns the structured output of the frozen Document
Pre-Analyzer, JEV Router, RAG Agent, Vision Agent and Analysis Agent into a
coherent, human-readable, evidence-grounded research critique.

Exports:
- CritiqueEngine: high-level orchestrator (one synthesis call, then validation)
- Synthesis context assembly: build_synthesis_context, ContextBuilderError
- Prompting: build_critique_prompt, RULE_BLOCK, OUTPUT_CONTRACT_HEADER
- Synthesis model abstraction: BaseCritiqueClient, OpenAICompatibleCritiqueClient
- Validation: validate_critique, validate_model_response, CritiqueValidationError
- Schemas: sections, source refs, claim summary, limitations, gaps, result
- Config: CritiqueConfig, CRITIQUE_LEVEL_MODELS, resolve_model_for_level
"""

from backend.critique_engine.config import (
    CRITIQUE_ALLOW_LEVEL_FALLBACK,
    CRITIQUE_JSON_RESPONSE_FORMAT,
    CRITIQUE_LEVEL_MODELS,
    LEVEL_ORDER,
    CritiqueConfig,
    CritiqueConfigurationError,
    normalize_level,
    resolve_model_for_level,
)
from backend.critique_engine.schemas import (
    ALWAYS_REQUIRED_SECTIONS,
    CLAIM_STATUSES,
    CRITIQUE_VERSION,
    SECTION_IDS,
    SECTION_TITLES,
    SOURCE_TYPES,
    UNCERTAINTY_MARKERS,
    AnalysisClaim,
    AnalysisDimensionSummary,
    AnalysisSummary,
    ClaimEvidenceSummaryItem,
    CritiqueFailure,
    CritiqueGap,
    CritiqueLimitations,
    CritiqueOpenQuestion,
    CritiqueOverallAssessment,
    CritiquePayload,
    CritiqueProvenance,
    CritiqueResult,
    CritiqueSection,
    CritiqueStrength,
    DocumentSummary,
    RetrievedEvidence,
    RoutingSummary,
    SectionSpec,
    SourceRef,
    SupportedSections,
    SynthesisContext,
    ValidationIssue,
    ValidationReport,
    VisualEvidence,
)
from backend.critique_engine.context_builder import (
    DIMENSION_TO_SECTION,
    ContextBuilderError,
    build_synthesis_context,
)
from backend.critique_engine.prompts import (
    OUTPUT_CONTRACT_HEADER,
    RULE_BLOCK,
    SECTION_EXPECTATIONS,
    build_context_block,
    build_critique_prompt,
    render_gaps_block,
    render_section_guidance,
    render_source_index_block,
)
from backend.critique_engine.llm_client import (
    CritiqueAuthError,
    CritiqueClientError,
    CritiqueModelUnavailableError,
    CritiqueResponseError,
    BaseCritiqueClient,
    OpenAICompatibleCritiqueClient,
    build_critique_client,
    mask_secret,
    resolve_api_key,
)
from backend.critique_engine.validator import (
    FORBIDDEN_KEYS,
    SCORE_PATTERNS,
    SECRET_PATTERNS,
    CritiqueValidationError,
    detect_score_like_text,
    detect_secrets,
    detect_unsupported_verdicts,
    extract_json_payload,
    extract_page_citations,
    find_forbidden_keys,
    is_uncertain_text,
    validate_critique,
    validate_model_response,
)
from backend.critique_engine.engine import CritiqueEngine

__all__ = [
    "CRITIQUE_ALLOW_LEVEL_FALLBACK",
    "CRITIQUE_JSON_RESPONSE_FORMAT",
    "CRITIQUE_LEVEL_MODELS",
    "CRITIQUE_VERSION",
    "LEVEL_ORDER",
    "CritiqueConfig",
    "CritiqueConfigurationError",
    "normalize_level",
    "resolve_model_for_level",
    "ALWAYS_REQUIRED_SECTIONS",
    "CLAIM_STATUSES",
    "SECTION_IDS",
    "SECTION_TITLES",
    "SOURCE_TYPES",
    "UNCERTAINTY_MARKERS",
    "AnalysisClaim",
    "AnalysisDimensionSummary",
    "AnalysisSummary",
    "ClaimEvidenceSummaryItem",
    "CritiqueFailure",
    "CritiqueGap",
    "CritiqueLimitations",
    "CritiqueOpenQuestion",
    "CritiqueOverallAssessment",
    "CritiquePayload",
    "CritiqueProvenance",
    "CritiqueResult",
    "CritiqueSection",
    "CritiqueStrength",
    "DocumentSummary",
    "RetrievedEvidence",
    "RoutingSummary",
    "SectionSpec",
    "SourceRef",
    "SupportedSections",
    "SynthesisContext",
    "ValidationIssue",
    "ValidationReport",
    "VisualEvidence",
    "DIMENSION_TO_SECTION",
    "ContextBuilderError",
    "build_synthesis_context",
    "OUTPUT_CONTRACT_HEADER",
    "RULE_BLOCK",
    "SECTION_EXPECTATIONS",
    "build_context_block",
    "build_critique_prompt",
    "render_gaps_block",
    "render_section_guidance",
    "render_source_index_block",
    "CritiqueAuthError",
    "CritiqueClientError",
    "CritiqueModelUnavailableError",
    "CritiqueResponseError",
    "BaseCritiqueClient",
    "OpenAICompatibleCritiqueClient",
    "build_critique_client",
    "mask_secret",
    "resolve_api_key",
    "FORBIDDEN_KEYS",
    "SCORE_PATTERNS",
    "SECRET_PATTERNS",
    "CritiqueValidationError",
    "detect_score_like_text",
    "detect_secrets",
    "detect_unsupported_verdicts",
    "extract_json_payload",
    "extract_page_citations",
    "find_forbidden_keys",
    "is_uncertain_text",
    "validate_critique",
    "validate_model_response",
    "CritiqueEngine",
]